# Generated by Django 2.2 on 2020-02-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(upload_to='projects/images/')),
            ],
        ),
    ]
